name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install backend dependencies
        run: npm install

      - name: Install frontend dependencies
        working-directory: ./puhelinluettelo_frontend
        run: npm install

      - name: Check style
        run: npm run lint

      - name: Build
        run: npm run build:ui

      - name: Render Deploy Action
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}

      - name: Discord Deployment Success
        uses: stegzilla/discord-notify@v2
        if: ${{ success() && (github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip'))}}
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Deployment Succeeded
          message: 'https://cicd-puhelinluettelo-3cqb.onrender.com'
          username: Puhelinluettelo
          colour: '#00ff00'

      - name: Discord Build Fail
        uses: stegzilla/discord-notify@v2
        if: failure()
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Build Failed
          message: 'Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }} failed'
          username: Puhelinluettelo
          colour: '#ff0000'
